- name: send Dockerfile
  copy:
    src: ../files/Dockerfile
    dest: /home/{{user}}/docker/{{app_name}}/
    owner: "{{user}}"
    group: "{{user}}"
    mode: u=r,g=r,o=r

- name: send docker-compose.yml
  copy:
    src: ../files/docker-compose.yml
    dest: /home/{{user}}/docker/{{app_name}}/
    owner: "{{user}}"
    group: "{{user}}"
    mode: u=r,g=r,o=r

- name: create launch script and give permissions
  file:
    name: /home/{{user}}/docker/{{app_name}}/{{script_name}}.sh
    state: touch
    owner: "{{user}}"
    group: "{{user}}"
    mode: u=rx,g=r,o=r

- name: fill launch script
  shell: echo "docker-compose -f /home/{{user}}/docker/{{app_name}}/docker-compose.yml up -d" > /home/{{user}}/docker/{{app_name}}/{{script_name}}.sh

- name: execute launch script
  shell: /home/{{user}}/docker/{{app_name}}/{{script_name}}.sh

- name: add job to root's crontab
  cron:
    name: launch mosquitto container
    special_time: reboot
    job: "/home/{{user}}/docker/{{app_name}}/{{script_name}}.sh"
    user: root
    state: present