---
- name: mosquitto-playbook
  hosts: rasp-01
  become: yes
  become_method: sudo
  vars:
    app_name: mosquitto
  tasks:
  - import_role:
      name: ../roles/install-docker
  - import_role:
      name: ../roles/deploy-mosquitto-container