- name: update cache
  apt:
    update_cache: yes
    
- name: download docker installation script
  get_url:
    url: https://get.docker.com
    dest: /tmp/get-docker.sh
    owner: "{{user}}"
    mode: '0111'

- name: execute docker installation script
  shell: /tmp/get-docker.sh

- name: delete docker installation script
  file:
    path: /tmp/get-docker.sh
    state: absent

- name: add user to docker group
  user:
    name: "{{user}}"
    groups:
    - docker
    append: yes